; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	madhephaestus/ESP32Encoder@^0.12.0

[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	adafruit/Adafruit BusIO @ ^1.14.0
	adafruit/Adafruit GFX Library @ ^1.12.0
	https://github.com/adafruit/Adafruit_GC9A01A.git
	madhephaestus/ESP32Encoder@^0.12.0

build_flags = 
	-D USER_SETUP_LOADED=1
	-D GC9A01_DRIVER
	
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=240
	
	-D TFT_MOSI=23
	-D TFT_SCLK=18
	-D TFT_CS=5
	-D TFT_DC=2
	-D TFT_RST=4
	
	-D ENC_CLK=32
	-D ENC_DT=33
	-D ENC_SW=25
	
	-D SPI_FREQUENCY=40000000

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM15
; build_type = debug
lib_deps = 
	adafruit/Adafruit BusIO @ ^1.14.0
	adafruit/Adafruit GFX Library @ ^1.12.0
	https://github.com/adafruit/Adafruit_GC9A01A.git
	madhephaestus/ESP32Encoder@^0.12.0
build_flags = 
	-D USER_SETUP_LOADED=1
	-D GC9A01_DRIVER
	
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=240

	-D TFT_SDA=35
	-D TFT_SCL=36
	-D TFT_DC=38
	-D TFT_CS=39
	-D TFT_RST=40
	
	-D ENC_SW=15
	-D ENC_DT=16
	-D ENC_CLK=17
	
	-D SPI_FREQUENCY=40000000

	-D B0_PIN=10
	-D B1_PIN=11
	-D B2_PIN=12
