[env:pico]
platform = raspberrypi
board = pico
framework = arduino
lib_deps = bodmer/TFT_eSPI@^2.5.43


[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit BusIO @ ^1.14.0
    adafruit/Adafruit GFX Library @ ^1.12.0
    https://github.com/adafruit/Adafruit_GC9A01A.git

build_flags =
    -D USER_SETUP_LOADED=1
    -D GC9A01_DRIVER

    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240

    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=4

    -D ENC_CLK=32
    -D ENC_DT=33
    -D ENC_SW=25

    -D SPI_FREQUENCY=40000000
